In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cpu


# Introduction to Tensors

### Creating Tensors

In [15]:
#scalar
scalar = torch.tensor(7) #in pyTorch, tensors are created like this
scalar

tensor(7)

In [7]:
#to get the tensor-scalar back into the integer '7' form
scalar.item()

7

In [8]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [10]:
#matrix
matrix = torch.tensor([[7, 8],
                        [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [13]:
#tensors
tensors = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
tensors

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensors.ndim, tensors.shape

(3, torch.Size([1, 3, 3]))

 ### Random Tensors

In [18]:
random_tensor = torch.rand(3, 4)

In [19]:
random_tensor

tensor([[0.8005, 0.4598, 0.9235, 0.7265],
        [0.7706, 0.2868, 0.2026, 0.6557],
        [0.2204, 0.1998, 0.0582, 0.0920]])

In [20]:
random_tensor = torch.rand(1, 10, 10)

In [21]:
random_tensor

tensor([[[0.6355, 0.0215, 0.7035, 0.8435, 0.7095, 0.8573, 0.7939, 0.0545,
          0.8590, 0.7255],
         [0.8406, 0.5532, 0.4146, 0.3808, 0.0777, 0.8394, 0.1169, 0.4447,
          0.2544, 0.3983],
         [0.9711, 0.3279, 0.4337, 0.7557, 0.1906, 0.6873, 0.7810, 0.6708,
          0.1370, 0.9698],
         [0.9962, 0.7783, 0.5215, 0.2413, 0.2472, 0.9008, 0.4640, 0.2661,
          0.3255, 0.1718],
         [0.2742, 0.5558, 0.8122, 0.7608, 0.3129, 0.6925, 0.9170, 0.4786,
          0.2705, 0.2930],
         [0.2946, 0.6900, 0.8525, 0.0029, 0.4393, 0.6477, 0.1156, 0.5181,
          0.4160, 0.6755],
         [0.6679, 0.2686, 0.0567, 0.5600, 0.7845, 0.9124, 0.0492, 0.8888,
          0.3522, 0.0351],
         [0.0778, 0.4552, 0.5218, 0.9729, 0.7904, 0.6739, 0.6315, 0.9256,
          0.4524, 0.6029],
         [0.1555, 0.4718, 0.5051, 0.0537, 0.6211, 0.0840, 0.9000, 0.9369,
          0.4219, 0.5087],
         [0.2073, 0.0194, 0.6556, 0.4871, 0.8067, 0.8902, 0.0019, 0.8300,
          0.9414,

In [25]:
#create a random tensor with a similar shape to an image tensor
random_img_tensor = torch.rand(size = (224, 224, 3))
# the first parameter denotes the height, the second denotes the width and the third denotes the number of color channels RGB

In [28]:
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [29]:
zeros = torch.zeros(size=(3,4))

In [30]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### creating range of tensors and tensor-like

In [34]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [40]:
float16_tensor = torch.tensor([3.9, 9.2, 7.6], dtype=torch.float16)

In [41]:
float16_tensor

tensor([3.9004, 9.2031, 7.6016], dtype=torch.float16)

In [42]:
int32_tensor = torch.tensor([3.9, 9.2, 7.6], dtype=torch.int32)

In [43]:
int32_tensor

tensor([3, 9, 7], dtype=torch.int32)

In [44]:
float16_tensor * int32_tensor

tensor([11.7031, 82.8125, 53.2188], dtype=torch.float16)

### manipulating tensors

In [46]:
tensors

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [47]:
tensors+100

tensor([[[101, 102, 103],
         [104, 105, 106],
         [107, 108, 109]]])

In [51]:
tensors-100

tensor([[[-99, -98, -97],
         [-96, -95, -94],
         [-93, -92, -91]]])

In [49]:
tensors*100

tensor([[[100, 200, 300],
         [400, 500, 600],
         [700, 800, 900]]])

In [50]:
tensors/100

tensor([[[0.0100, 0.0200, 0.0300],
         [0.0400, 0.0500, 0.0600],
         [0.0700, 0.0800, 0.0900]]])

 ### matrix multiplication

In [53]:
t1 = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
t2 = torch.tensor([[9, 8],
                  [7, 6],
                  [5, 4],
                  [3, 2]])

In [54]:
t1.shape, t2.shape

(torch.Size([2, 4]), torch.Size([4, 2]))

In [55]:
torch.matmul(t1, t2)

tensor([[ 50,  40],
        [146, 120]])

In [56]:
torch.matmul(t2, t1)

tensor([[ 49,  66,  83, 100],
        [ 37,  50,  63,  76],
        [ 25,  34,  43,  52],
        [ 13,  18,  23,  28]])

### finding min, max, mean and sum and etc(tensor aggregation)

In [61]:
x = torch.arange(1, 100, 1)
x = x.type(torch.float32)

In [62]:
torch.min(x)

tensor(1.)

In [63]:
torch.max(x)

tensor(99.)

In [64]:
torch.mean(x)

tensor(50.)

In [65]:
torch.sum(x)

tensor(4950.)

### finding positional min and max

In [66]:
x.argmin() #returns the index of the min value in the tensor

tensor(0)

In [67]:
x.argmax()

tensor(98)

### reshaping, viewing, squeezing and unsqueezing and stacking

In [71]:
t1_reshape = t1.reshape(4, 2)
t1_reshape

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [74]:
t1_view = t1.view(2, 4) #view shares the same memory as the original tensor, so making a change in the view will reflect in the original tensor

In [75]:
t1_view[:, 3] = 4

In [76]:
t1_view

tensor([[1, 2, 3, 4],
        [5, 6, 7, 4]])

In [77]:
t1

tensor([[1, 2, 3, 4],
        [5, 6, 7, 4]])

In [81]:
t1_stack = torch.stack([t1, t1, t1], dim=0)

In [82]:
t1_stack

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 4]],

        [[1, 2, 3, 4],
         [5, 6, 7, 4]],

        [[1, 2, 3, 4],
         [5, 6, 7, 4]]])

In [83]:
t1_stack = torch.stack([t1, t1, t1], dim=1)

In [84]:
t1_stack

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[5, 6, 7, 4],
         [5, 6, 7, 4],
         [5, 6, 7, 4]]])

In [85]:
t1_stack = torch.stack([t1, t1, t1], dim=2)

In [86]:
t1_stack

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],

        [[5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [4, 4, 4]]])

In [87]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

#### torch.squeeze() - removes all single '1' dimensions from the target tensor

In [88]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [92]:
y = torch.squeeze(x, 0)
y.size()
#removes the single dimension from 0th position in the size

torch.Size([2, 1, 2, 1, 2])

In [93]:
y = torch.squeeze(x, 1)
y.size()
#removess the single dimension from the 1th position in the size

torch.Size([2, 2, 1, 2])

#### torch.unsqueeze() - adds a single '1' dimension to a target tensor at a specific dimension

In [94]:
y = torch.unsqueeze(y, 0)
y.size()
#adds single dimension to the 0th position

torch.Size([1, 2, 2, 1, 2])

In [96]:
y = torch.unsqueeze(y, 1)
y.size()
#adds single dimension to the 1th position

torch.Size([1, 1, 1, 2, 2, 1, 2])

#### torch.permute() function is used to rearrange the dimensions of a tensor

In [97]:
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [100]:
torch.permute(x, (2,0,1)).size() #2nd dimension is at 0th place, 0th dimension is at 1st place and 1st dimension is at 2nd place

torch.Size([5, 2, 3])

### selecting data from tensors (indexing)

In [102]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [103]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [106]:
x[0, 0], x[0, 1], x[0, 2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [108]:
x[0, 0, 0], x[0, 0, 1], x[0, 0, 2], x[0, 1, 0], x[0, 1, 1]

(tensor(1), tensor(2), tensor(3), tensor(4), tensor(5))

### PyTorch Tensors and NumPy

##### torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
##### torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [113]:
nparr = np.arange(1.0, 10.0)
tensnp = torch.from_numpy(nparr) #converting np array to tensor
nparr, tensnp

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [114]:
nptens = tensnp.numpy() #converting tensor to np array
nptens

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

###  Reproducibility (trying to take the random out of random

In [115]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2888, 0.7797, 0.1902, 0.0087],
        [0.2103, 0.3258, 0.7130, 0.1701],
        [0.4072, 0.6640, 0.4310, 0.5891]])

Tensor B:
tensor([[0.7877, 0.4516, 0.2231, 0.9750],
        [0.8885, 0.2240, 0.4206, 0.9854],
        [0.6128, 0.2512, 0.7872, 0.6909]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [116]:
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

To check if we've got access to a Nvidia GPU, we can run !nvidia-smi where the ! (also called bang) means "run this on the command line".

In [117]:
!nvidia-smi

Sat Apr 13 22:42:55 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.68                 Driver Version: 531.68       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650       WDDM | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8                4W /  N/A|      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--